[package]
name = "gml-run"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
fabricator-vm = { git = "https://github.com/kyren/fabricator" }
fabricator-compiler = { git = "https://github.com/kyren/fabricator" }
fabricator-stdlib = { git = "https://github.com/kyren/fabricator" }

[profile.release]
lto = "fat"
codegen-units = 1

[workspace]
