use chompy::lex::TokenKind;
use std::fmt::Display;

/// An individual tok of mimas.
#[derive(Debug, PartialEq, Clone, Copy)]
pub enum TokKind<'s> {
    Match,
    Break,
    Collect,
    Return,
    Raise,
    Absolve,
    Struct,
    Impl,
    Pact,
    Const,
    Pub,
    Module,
    At,
    Colon,
    DoubleColon,
    Dot,
    DoubleDot,
    DoubleDotEqual,
    LeftSquare,
    RightSquare,
    Enum,
    LeftBrace,
    RightBrace,
    TildeLeftBrace,
    LeftParenthesis,
    RightParenthesis,
    Comma,
    Ampersand,
    DoubleAmpersand,
    DoublePipe,
    Caret,
    Equal,
    DoubleEqual,
    BangEqual,
    Fn,
    SelfKeyword,
    Percent,
    PercentEqual,
    TildeSlash,
    TildeSlashEqual,
    Slash,
    Star,
    True,
    False,
    Plus,
    Minus,
    Bang,
    Hook,
    DoubleHook,
    DoubleHookEqual,
    HookDot,
    HookLeftSquare,
    Greater,
    GreaterEqual,
    Less,
    LessEqual,
    Pipe,
    SemiColon,
    If,
    Else,
    For,
    NotIn,
    In,
    Loop,
    While,
    Let,
    PlusEqual,
    MinusEqual,
    StarEqual,
    SlashEqual,
    PipeEqual,
    AmpersandEqual,
    CaretEqual,
    Tilde,
    DoubleLeftCaret,
    DoubleRightCaret,
    Continue,
    Null,
    Use,
    Arrow,
    FatArrow,
    TyKw(TyKw),
    Ident(&'s str),
    Int(i64),
    Float(f64),
    String(&'s str),
    FString(&'s str),
    Hex(&'s str),
    Invalid(&'s str),
}

#[mutants::skip]
impl Display for TokKind<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            TokKind::Match => "match",
            TokKind::Break => "break",
            TokKind::Collect => "collect",
            TokKind::Return => "return",
            TokKind::Raise => "raise",
            TokKind::Absolve => "absolve",
            TokKind::Struct => "struct",
            TokKind::Pact => "pact",
            TokKind::Impl => "impl",
            TokKind::Const => "const",
            TokKind::Pub => "pub",
            TokKind::Module => "module",
            TokKind::At => "@",
            TokKind::Colon => ":",
            TokKind::DoubleColon => "::",
            TokKind::Dot => ".",
            TokKind::DoubleDot => "..",
            TokKind::DoubleDotEqual => "..=",
            TokKind::LeftSquare => "[",
            TokKind::RightSquare => "]",
            TokKind::Enum => "enum",
            TokKind::LeftBrace => "{",
            TokKind::RightBrace => "}",
            TokKind::TildeLeftBrace => "~{",
            TokKind::LeftParenthesis => "(",
            TokKind::RightParenthesis => ")",
            TokKind::Comma => ",",
            TokKind::Ampersand => "&",
            TokKind::DoubleAmpersand => "&&",
            TokKind::DoublePipe => "||",
            TokKind::Caret => "^",
            TokKind::Equal => "=",
            TokKind::DoubleEqual => "==",
            TokKind::BangEqual => "!=",
            TokKind::Fn => "fn",
            TokKind::SelfKeyword => "self",
            TokKind::Percent => "%",
            TokKind::PercentEqual => "%=",
            TokKind::TildeSlash => "~/",
            TokKind::TildeSlashEqual => "~/=",
            TokKind::Slash => "/",
            TokKind::Star => "*",
            TokKind::True => "true",
            TokKind::False => "false",
            TokKind::Plus => "+",
            TokKind::Minus => "-",
            TokKind::Bang => "!",
            TokKind::Hook => "?",
            TokKind::DoubleHook => "??",
            TokKind::DoubleHookEqual => "??=",
            TokKind::HookDot => "?.",
            TokKind::HookLeftSquare => "?[",
            TokKind::Greater => ">",
            TokKind::GreaterEqual => ">=",
            TokKind::Less => "<",
            TokKind::LessEqual => "<=",
            TokKind::Pipe => "|",
            TokKind::SemiColon => ";",
            TokKind::If => "if",
            TokKind::Else => "else",
            TokKind::For => "for",
            TokKind::In => "in",
            TokKind::NotIn => "!in",
            TokKind::Loop => "loop",
            TokKind::While => "while",
            TokKind::Let => "let",
            TokKind::PlusEqual => "+=",
            TokKind::MinusEqual => "-=",
            TokKind::StarEqual => "*=",
            TokKind::SlashEqual => "/=",
            TokKind::PipeEqual => "|=",
            TokKind::AmpersandEqual => "&=",
            TokKind::CaretEqual => "^=",
            TokKind::Tilde => "~",
            TokKind::DoubleLeftCaret => "<<",
            TokKind::DoubleRightCaret => ">>",
            TokKind::Continue => "continue",
            TokKind::Null => "null",
            TokKind::Use => "use",
            TokKind::Arrow => "->",
            TokKind::FatArrow => "=>",
            TokKind::TyKw(tym) => return f.pad(&tym.to_string()),
            TokKind::Ident(iden) => iden,
            TokKind::Int(r) => return f.pad(&r.to_string()),
            TokKind::Float(r) => return f.pad(&r.to_string()),
            TokKind::String(s) => return f.pad(&format!("\"{s}\"")),
            TokKind::FString(s) => return f.pad(&format!("f\"{s}\"")),
            TokKind::Hex(hex) => hex,
            TokKind::Invalid(_) => "INVALID_TOKEN",
        };
        f.pad(s)
    }
}

impl TokenKind for TokKind<'_> {}

#[derive(Debug, Copy, PartialEq, Clone)]
pub enum TyKw {
    Int,
    Float,
    Str,
    Bool,
}

#[mutants::skip]
impl std::fmt::Display for TyKw {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TyKw::Int => f.pad("int"),
            TyKw::Float => f.pad("float"),
            TyKw::Str => f.pad("str"),
            TyKw::Bool => f.pad("bool"),
        }
    }
}
