[package]
name = "mimas-bevy"
version = "0.1.0"
edition = "2024"
description = "todo"
license = "MIT OR Apache-2.0"
repository = "https://github.com/imlazyeye/mimas"
homepage = "https://mim.as"
rust-version = "1.95"

[dependencies]
api = { package = "mimas-api", path = "../api", version = "0.1.0" }
compile = { package = "mimas-compile", path = "../compile", version = "0.1.0" }
library = { package = "mimas-library", path = "../library", version = "0.1.0" }
macros = { package = "mimas-macros", path = "../macros", version = "0.1.0" }
parse = { package = "mimas-parse", path = "../parse", version = "0.1.0" }
shared = { package = "mimas-shared", path = "../shared", version = "0.1.0" }
vm = { package = "mimas-vm", path = "../vm", version = "0.1.0" }
miette = { version = "7.6", features = ["fancy"] }
bevy = { version = "0.19.1", default-features = false, features = [
    "std",
    "bevy_asset",
    "bevy_camera",
    "bevy_log",
    "bevy_window",
    "keyboard",
    "mouse",
    "reflect_auto_register",
] }

[dev-dependencies]
criterion = "0.5"

[[test]]
name = "bevy"

[[bench]]
name = "hook_benches"
harness = false
